#!/usr/bin/env python3
# Generate src/arabicfont.c: a 16x16 bitmap Arabic font (the 4 contextual
# forms of each letter), rasterised from GeezaPro, plus a letter table the
# kernel's shaper uses. Also previews shaped words as ASCII art.
from PIL import Image, ImageFont, ImageDraw

FONT = "/System/Library/Fonts/GeezaPro.ttc"
SIZE = 15
CELL_W, CELL_H = 16, 16
BASELINE = 12          # baseline row inside the cell (descenders go below)

# base cp -> (class, iso, fin, init, med). class: 2=dual,1=right,0=none.
# A form of 0 means "use the isolated/final fallback".
L = {
 0x0621:(0,0xFE80,0,0,0),
 0x0622:(1,0xFE81,0xFE82,0,0), 0x0623:(1,0xFE83,0xFE84,0,0),
 0x0624:(1,0xFE85,0xFE86,0,0), 0x0625:(1,0xFE87,0xFE88,0,0),
 0x0626:(2,0xFE89,0xFE8A,0xFE8B,0xFE8C), 0x0627:(1,0xFE8D,0xFE8E,0,0),
 0x0628:(2,0xFE8F,0xFE90,0xFE91,0xFE92), 0x0629:(1,0xFE93,0xFE94,0,0),
 0x062A:(2,0xFE95,0xFE96,0xFE97,0xFE98), 0x062B:(2,0xFE99,0xFE9A,0xFE9B,0xFE9C),
 0x062C:(2,0xFE9D,0xFE9E,0xFE9F,0xFEA0), 0x062D:(2,0xFEA1,0xFEA2,0xFEA3,0xFEA4),
 0x062E:(2,0xFEA5,0xFEA6,0xFEA7,0xFEA8), 0x062F:(1,0xFEA9,0xFEAA,0,0),
 0x0630:(1,0xFEAB,0xFEAC,0,0), 0x0631:(1,0xFEAD,0xFEAE,0,0),
 0x0632:(1,0xFEAF,0xFEB0,0,0), 0x0633:(2,0xFEB1,0xFEB2,0xFEB3,0xFEB4),
 0x0634:(2,0xFEB5,0xFEB6,0xFEB7,0xFEB8), 0x0635:(2,0xFEB9,0xFEBA,0xFEBB,0xFEBC),
 0x0636:(2,0xFEBD,0xFEBE,0xFEBF,0xFEC0), 0x0637:(2,0xFEC1,0xFEC2,0xFEC3,0xFEC4),
 0x0638:(2,0xFEC5,0xFEC6,0xFEC7,0xFEC8), 0x0639:(2,0xFEC9,0xFECA,0xFECB,0xFECC),
 0x063A:(2,0xFECD,0xFECE,0xFECF,0xFED0), 0x0641:(2,0xFED1,0xFED2,0xFED3,0xFED4),
 0x0642:(2,0xFED5,0xFED6,0xFED7,0xFED8), 0x0643:(2,0xFED9,0xFEDA,0xFEDB,0xFEDC),
 0x0644:(2,0xFEDD,0xFEDE,0xFEDF,0xFEE0), 0x0645:(2,0xFEE1,0xFEE2,0xFEE3,0xFEE4),
 0x0646:(2,0xFEE5,0xFEE6,0xFEE7,0xFEE8), 0x0647:(2,0xFEE9,0xFEEA,0xFEEB,0xFEEC),
 0x0648:(1,0xFEED,0xFEEE,0,0), 0x0649:(1,0xFEEF,0xFEF0,0,0),
 0x064A:(2,0xFEF1,0xFEF2,0xFEF3,0xFEF4),
}

fnt = ImageFont.truetype(FONT, SIZE)
asc, desc = fnt.getmetrics()

def raster(formcp):
    """Render a presentation-form codepoint into a 16x16 cell, baseline-aligned.
    Returns (rows[16] of 16-bit ints, advance)."""
    img = Image.new("L", (CELL_W, CELL_H), 0)
    d = ImageDraw.Draw(img)
    d.text((1, BASELINE - asc), chr(formcp), fill=255, font=fnt)
    px = img.load()
    rows = []
    maxx = 0
    for y in range(CELL_H):
        bits = 0
        for x in range(CELL_W):
            if px[x, y] > 110:
                bits |= (1 << x)            # LSB = leftmost (matches font8x8)
                if x > maxx: maxx = x
        rows.append(bits)
    adv = maxx + 2 if maxx else 8
    return rows, adv

# collect unique forms -> glyph index
glyphs = []          # list of (rows, adv)
index = {}           # formcp -> glyph idx
def add(cp):
    if cp == 0: return 255
    if cp in index: return index[cp]
    rows, adv = raster(cp)
    index[cp] = len(glyphs)
    glyphs.append((rows, adv))
    return index[cp]

letters = []   # (base, cls, iso, fin, init, med) as glyph indices
for base in sorted(L):
    cls, iso, fin, ini, med = L[base]
    gi = add(iso)
    gf = add(fin if fin else iso)
    gini = add(ini if ini else iso)
    gmed = add(med if med else (fin if fin else iso))
    letters.append((base, cls, gi, gf, gini, gmed))

# ---- emit C ----
with open("src/arabicfont.c", "w") as f:
    f.write("/* arabicfont.c - GENERATED by test/gen_arabicfont.py.\n"
            " * 16x16 bitmap Arabic glyphs (presentation forms) rasterised from\n"
            " * GeezaPro, plus the letter table the shaper (browser.c) uses. */\n")
    f.write('#include "arabicfont.h"\n\n')
    f.write(f"const int arabic_nglyph = {len(glyphs)};\n")
    f.write("const uint16_t arabic_glyphs[][16] = {\n")
    for rows, adv in glyphs:
        f.write("  {" + ",".join(f"0x{r:04x}" for r in rows) + "},\n")
    f.write("};\n\n")
    f.write("const uint8_t arabic_advance[] = {\n  ")
    f.write(",".join(str(adv) for _, adv in glyphs))
    f.write("\n};\n\n")
    f.write(f"const int arabic_nletters = {len(letters)};\n")
    f.write("const struct arabic_letter arabic_letters[] = {\n")
    for base, cls, gi, gf, gini, gmed in letters:
        f.write(f"  {{0x{base:04x},{cls},{gi},{gf},{gini},{gmed}}},\n")
    f.write("};\n")

with open("src/arabicfont.h", "w") as f:
    f.write("#pragma once\n#include <stdint.h>\n\n")
    f.write("/* A 16x16 Arabic glyph bitmap font + letter table (GENERATED).\n"
            " * Each glyph row is 16 bits, LSB = leftmost pixel. */\n")
    f.write("struct arabic_letter { int base; uint8_t cls; uint8_t iso,fin,init,med; };\n")
    f.write("extern const uint16_t arabic_glyphs[][16];\n")
    f.write("extern const uint8_t  arabic_advance[];\n")
    f.write("extern const int      arabic_nglyph;\n")
    f.write("extern const struct arabic_letter arabic_letters[];\n")
    f.write("extern const int      arabic_nletters;\n")

print(f"wrote src/arabicfont.c: {len(glyphs)} glyphs, {len(letters)} letters")

# ---- preview: shape + RTL-render a few words as ASCII art ----
bybase = {base:(cls,gi,gf,gini,gmed) for base,cls,gi,gf,gini,gmed in letters}
def shape(word):           # word: list of base cps (logical order)
    out = []
    for i,cp in enumerate(word):
        if cp not in bybase: continue
        cls,gi,gf,gini,gmed = bybase[cp]
        prevc = bybase[word[i-1]][0] if i>0 and word[i-1] in bybase else 0
        nextc = bybase[word[i+1]][0] if i+1<len(word) and word[i+1] in bybase else 0
        jp = (cls>=1) and (prevc==2)
        jn = (cls==2) and (nextc>=1)
        out.append(gmed if (jp and jn) else gf if jp else gini if jn else gi)
    return out

def preview(s):
    cps=[ord(c) for c in s]
    gl=shape(cps)[::-1]      # reverse for RTL (draw left->right)
    W=len(gl)*12+4
    canvas=[[0]*W for _ in range(16)]
    x=0
    for g in gl:
        for y in range(16):
            bits=arabic_glyphs_local[g][y]
            for b in range(16):
                if bits&(1<<b) and x+b<W: canvas[y][x+b]=1
        x+=12
    print(f"--- {s} ---")
    for y in range(16):
        print("".join("#" if canvas[y][x] else " " for x in range(W)))

arabic_glyphs_local=[rows for rows,_ in glyphs]
preview("مرحبا")
preview("العربي")
