#!/usr/bin/env python3
# Generate src/propfont.c: a proportional bitmap font (ASCII 0x20..0x7E)
# rasterised from Noto Sans 14px, for the browser's body text. Each glyph is
# up to 16px wide x 16px tall (uint16 rows, LSB=leftmost) with its own
# advance width — so text looks like a real page, not 8x8 blocks.
#
# Noto Sans is licensed under the SIL Open Font License 1.1 (free/open), so
# the generated table is freely redistributable. Get the font from
# https://fonts.google.com/noto/specimen/Noto+Sans (NotoSans-Regular.ttf).
# Override the path with MICROOS_LATIN_FONT=/path/to/font.ttf if needed.
import os
from PIL import Image, ImageFont, ImageDraw

FONT_NAME = "Noto Sans"
CANDIDATES = [
    os.environ.get("MICROOS_LATIN_FONT", ""),
    os.path.expanduser("~/Library/Fonts/NotoSans-Regular.ttf"),
    "/Library/Fonts/NotoSans-Regular.ttf",
    "/usr/share/fonts/truetype/noto/NotoSans-Regular.ttf",
    "/usr/share/fonts/noto/NotoSans-Regular.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",  # also free (Bitstream Vera)
]
FONT = next((p for p in CANDIDATES if p and os.path.exists(p)), None)
if not FONT:
    raise SystemExit("No free Latin font found. Install Noto Sans (SIL OFL) or set "
                     "MICROOS_LATIN_FONT=/path/to/NotoSans-Regular.ttf")

SIZE = 14
CELL_H = 16
BASELINE = 12

fnt = ImageFont.truetype(FONT, SIZE)
asc, desc = fnt.getmetrics()

rows_all = []
adv_all = []
for cp in range(0x20, 0x7F):
    ch = chr(cp)
    img = Image.new("L", (18, CELL_H), 0)
    d = ImageDraw.Draw(img)
    d.text((1, BASELINE - asc), ch, fill=255, font=fnt)
    px = img.load()
    rows = []
    for y in range(CELL_H):
        bits = 0
        for x in range(16):
            if px[x, y] > 110:
                bits |= (1 << x)            # LSB = leftmost
        rows.append(bits)
    adv = int(round(fnt.getlength(ch))) + 1
    if cp == 0x20:                          # space: ensure a sensible width
        adv = max(adv, 4)
    if adv < 2: adv = 2
    if adv > 16: adv = 16
    rows_all.append(rows)
    adv_all.append(adv)

with open("src/propfont.c", "w") as f:
    f.write("/* propfont.c - GENERATED by test/gen_propfont.py.\n"
            f" * Proportional 16x16 bitmap font ({FONT_NAME} {SIZE}px, SIL OFL),\n"
            " * ASCII 0x20..0x7E. Each row is 16 bits, LSB = leftmost;\n"
            " * advance is per-glyph. */\n")
    f.write('#include "propfont.h"\n\n')
    f.write(f"const int prop_baseline = {BASELINE};\n")
    f.write("const uint16_t prop_glyph[95][16] = {\n")
    for rows in rows_all:
        f.write("  {" + ",".join(f"0x{r:04x}" for r in rows) + "},\n")
    f.write("};\n\n")
    f.write("const uint8_t prop_adv[95] = {\n  ")
    f.write(",".join(str(a) for a in adv_all))
    f.write("\n};\n")

with open("src/propfont.h", "w") as f:
    f.write("#pragma once\n#include <stdint.h>\n\n")
    f.write("/* Proportional bitmap font for the browser (GENERATED).\n"
            " * Glyphs for ASCII 0x20..0x7E; row bits LSB=leftmost. */\n")
    f.write("extern const uint16_t prop_glyph[95][16];\n")
    f.write("extern const uint8_t  prop_adv[95];\n")
    f.write("extern const int      prop_baseline;\n")

# preview
print(f"font: {FONT}")
print("preview:")
def show(s):
    W = sum(adv_all[ord(c)-0x20] for c in s) + 2
    canvas = [[0]*W for _ in range(CELL_H)]
    x = 0
    for c in s:
        gi = ord(c)-0x20
        for y in range(CELL_H):
            b = rows_all[gi][y]
            for bx in range(16):
                if b & (1<<bx) and x+bx < W: canvas[y][x+bx] = 1
        x += adv_all[gi]
    for y in range(CELL_H):
        print("".join("#" if canvas[y][x] else " " for x in range(W)))
show("The quick brown fox. MicroOS 1.1!")
print("done: src/propfont.c")
