/* Host harness for js.c: runs scripts, prints DOM side effects. */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "../src/js.h"

void *kmalloc(unsigned long n){ return malloc(n); }
void  kfree(void *p){ free(p); }

static char elem[256] = "placeholder";
static void h_write(void*c,const char*s){ (void)c; printf("[write] %s\n", s); }
static void h_log(void*c,const char*s){ (void)c; printf("[log] %s\n", s); }
static void h_set(void*c,const char*id,const char*s){ (void)c; printf("[set #%s] %s\n", id, s); snprintf(elem,sizeof elem,"%s",s); }
static int  h_get(void*c,const char*id,char*o,int m){ (void)c;(void)id; snprintf(o,m,"%s",elem); return 0; }

static void run(const char *name, const char *src) {
    printf("=== %s ===\n", name);
    struct js_host h = { h_write, h_log, h_set, h_get, 0 };
    char err[64]="";
    int rc = js_run(src, &h, err, sizeof err);
    if (rc) printf("ERROR: %s\n", err);
    printf("\n");
}

int main(void) {
    run("arithmetic + strings",
        "var a = 6; var b = 7;\n"
        "console.log('6*7 =', a*b);\n"
        "console.log('concat', 'x' + (a+b) + 'y');\n"
        "console.log('mod', 17 % 5, 'div', 17 / 5);");

    run("if / comparisons",
        "var n = 10;\n"
        "if (n > 5 && n < 20) console.log('in range'); else console.log('no');\n"
        "console.log('eq', 3 == 3, 'ne', 'a' != 'b');");

    run("while loop sum",
        "var i = 1; var s = 0;\n"
        "while (i <= 100) { s = s + i; i = i + 1; }\n"
        "console.log('sum 1..100 =', s);");

    run("for loop",
        "var t = 0;\n"
        "for (var i = 0; i < 5; i = i + 1) { t = t + i*i; }\n"
        "console.log('sum of squares 0..4 =', t);");

    run("functions + recursion",
        "function fact(n){ if (n <= 1) return 1; return n * fact(n-1); }\n"
        "function fib(n){ if (n < 2) return n; return fib(n-1) + fib(n-2); }\n"
        "console.log('fact(6) =', fact(6));\n"
        "console.log('fib(10) =', fib(10));");

    run("closures",
        "function adder(x){ function add(y){ return x + y; } return add; }\n"
        "var add5 = adder(5);\n"
        "console.log('add5(3) =', add5(3));");

    run("DOM: document.write + getElementById",
        "document.write('<b>generated by JS</b>');\n"
        "var el = document.getElementById('out');\n"
        "console.log('before:', el.textContent);\n"
        "el.textContent = 'Hello from MicroOS JS!';\n"
        "console.log('after:', document.getElementById('out').textContent);");
    return 0;
}
